<?php

	header("Content-type: application/vnd.ms-excel");
	header("Content-Disposition: attachment; filename=JobLoadingSummary$_POST[year]-$_POST[month].xls");

	echo "<b>JOB LOADING MONTHLY SUMMARY</b><br>";
	echo "<b>Month:</b> $_POST[month]<br>";
	echo "<b>Year:</b> $_POST[year]<br><br>";

	include "../db.php";	
	include "../function.php";

	$selectSql = "SELECT * FROM staff order by staffName";

	echo "<table border=1>
			<thead><tr>
				<th>No</th>					
				<th>Member Name</th>
				<th>Position</th>
				<th>Dept.</th>
				<th>Project</th>
				<th>Job Name</th>";

	for($i = 1; $i < 32; $i++){		
		$timestamp = strtotime("$_POST[year]-$_POST[month]-$i");
		$day = date('D', $timestamp);
		
		if($day == 'Sun' || $day == 'Sat'){
			echo "<th style='color:red;'>$i<br>$day</th>";
		}else {
			echo "<th>$i<br>$day</th>";
		}
	}
	echo "	<th>Total Month Hour</th>
		</tr></thead>";

	$no = 1;
	$staffCurrent = '';
	$staffIndex = 0;
	$jobRank = 0;
	$selectResult = $conn->query($selectSql);
	while($row = mysqli_fetch_assoc($selectResult)) {
		
		if($row['staffName'] != $staffCurrent){
			$staffCurrent = $row['staffName'];
			$row['staffName'] = strtoupper($row['staffName']);

			$selectSql2 = "SELECT * FROM data WHERE staffName='$row[staffName]'
								AND MONTH(jobDate)=$_POST[month] AND YEAR(jobDate)=$_POST[year] 
								ORDER By projectCode,jobName";			
			
			$monthHour = 0;
			$jobCurrent = "";
			$projectCurrent = "";

			$selectResult2 = $conn->query($selectSql2);
			while($row2 = mysqli_fetch_assoc($selectResult2)) {
				if($jobCurrent != $row2['jobName'] && $jobCurrent != $row2['projectCode']){
					$jobCurrent = $row2['jobName'];
					$projectCurrent = $row2['projectCode'];

					echo "<tr style='vertical-align: middle;'>
						<td style='text-align:center;'>$no.</td>
						<td>$row[staffName]</td>
						<td style='text-align:center;'>$row[jobTitle]</td>
						<td style='text-align:center;'>$row[deptCode]</td>
						<td style='text-align:center;'>$projectCurrent</td>
						<td>$jobCurrent</td>";

					for($i = 1; $i < 32; $i++){		
						$timestamp = strtotime("$_POST[year]-$_POST[month]-$i");
						$day = date('D', $timestamp);
						
						$selectSql3 = "SELECT * FROM data WHERE staffName='$row[staffName]'
									AND jobName='$jobCurrent' AND projectCode='$projectCurrent' AND DAY(jobDate)=$i AND MONTH(jobDate)=$_POST[month] AND YEAR(jobDate)=$_POST[year] 
									ORDER By jobHour+0 desc";
						
						$dayHour = 0;
						$selectResult3 = $conn->query($selectSql3);
						if($selectResult3->num_rows > 0){
							while($row3 = mysqli_fetch_assoc($selectResult3)) {
								$dayHour += $row3['jobHour'];
								$monthHour += $row3['jobHour'];
							}
						}

						if($day == 'Sun' || $day == 'Sat'){
							echo "<td  style='color:red;text-align:center;background-color:#ffd6d6;'>";
						}else {
							echo "<td style='text-align:center;'>";
						}
						if($dayHour == 0) $dayHour = "-";
						
						echo "$dayHour</td>";
					}

					echo "<td id='tabletotal'>$monthHour</td>";
					echo "</tr>";
					$no++;		
				}
			}
					
				
		}
		
	}

	echo "</table><br>";

	echo "<i>*Generated by Job Loading System.</i>";

?>