<?php

	header("Content-type: application/vnd.ms-excel");
	header("Content-Disposition: attachment; filename=DepartmentReport$_POST[year]-$_POST[month].xls");

	echo "<b>DEPARTMENT REPORT</b><br>";
	echo "<b>Month:</b> $_POST[month]<br>";
	echo "<b>Year:</b> $_POST[year]<br><br>";

	include "../db.php";	
	include "../function.php";

	$selectSql = "SELECT * FROM data WHERE MONTH(jobDate)=$_POST[month] 
				AND YEAR(jobDate)=$_POST[year] 
				order by deptCode,jobName";

	echo "<table border=1>
			<thead><tr>
				<th>No</th>
				<th>Dept. Code</th>
				<th>Dept. Name</th>
				<th>Job Name</th>
				<th>Hours</th>
			</tr></thead>";

	$deptCurrent = '';
	$deptName = '';
	$deptHour = 0;
	$no = 1;

	$selectResult = $conn->query($selectSql);
	while($row = mysqli_fetch_assoc($selectResult)) {
		$deptHour = 0;
		if($row['deptCode'] != $deptCurrent){
			$deptCurrent = $row['deptCode'];

			// get dept name
			$selectSql2 = "SELECT * FROM dept 
				WHERE deptCode='$deptCurrent'";

			$selectResult2 = $conn->query($selectSql2);
			while($row2 = mysqli_fetch_assoc($selectResult2)) {
				$deptName = $row2['deptName'];
				break;
			}

			$selectSql2 = "SELECT * FROM data WHERE MONTH(jobDate)=$_POST[month] 
			AND YEAR(jobDate)=$_POST[year] AND deptCode='$deptCurrent' 
			order by jobName,jobDate";

			$jobCurrent = '';			

			$selectResult2 = $conn->query($selectSql2);
			while($row2 = mysqli_fetch_assoc($selectResult2)) {

				$jobHour = 0;
				if($jobCurrent != $row2['jobName']){
					$jobCurrent = $row2['jobName'];

					echo "<tr  style='vertical-align:middle;'>
							<td style='text-align:center;'>$no.</td>
							<td style='text-align:center;'>$deptCurrent</td>
							<td style='text-align:center;'>$deptName</td>
							<td>$jobCurrent</td>";

					$selectSql3 = "SELECT * FROM data 
						WHERE MONTH(jobDate)=$_POST[month] 
						AND YEAR(jobDate)=$_POST[year]
						AND deptCode='$deptCurrent'
						AND jobName='$jobCurrent'";

					$selectResult3 = $conn->query($selectSql3);
					while($row3 = mysqli_fetch_assoc($selectResult3)) {
						$jobHour += $row3['jobHour'];
						$totalHour += $row3['jobHour'];
					}

					echo "	<td style='text-align:center;'>$jobHour</td>
						</tr>";
					$no++;
				}
			}					
		}
	}
	
	echo "</table><br>";

	echo "<i>*Generated by Job Loading System.</i>";

?>