<?php

	header("Content-type: application/vnd.ms-excel");
	header("Content-Disposition: attachment; filename=JobReport$_POST[year]-$_POST[month].xls");

	echo "<b>JOB REPORT</b><br>";
	echo "<b>Month:</b> $_POST[month]<br>";
	echo "<b>Year:</b> $_POST[year]<br><br>";

	include "../db.php";	
	include "../function.php";

	$selectSql = "SELECT * FROM data WHERE MONTH(jobDate)=$_POST[month] 
				AND YEAR(jobDate)=$_POST[year]
				order by jobName,jobDesc";

	echo "<table border=1>
			<thead><tr>
				<th>No</th>
				<th>Job Name</th>
				<th>Job Description</th>
				<th>Hours</th>
			</tr></thead>";

	$jobCurrent = '';
	$descCurrent = '';
	$no = 1;

	$selectResult = $conn->query($selectSql);
	while($row = mysqli_fetch_assoc($selectResult)) {
		$jobHour = 0;
		if($row['jobName'] != $jobCurrent || $descCurrent != $row['jobDesc']){
			$jobCurrent = $row['jobName'];
			$descCurrent = $row['jobDesc'];

			$selectSql2 = "SELECT * FROM data WHERE MONTH(jobDate)=$_POST[month] 
			AND YEAR(jobDate)=$_POST[year] AND jobName='$jobCurrent' AND jobDesc='$descCurrent'";						

			$jobHour = 0;	
			$selectResult2 = $conn->query($selectSql2);
			while($row2 = mysqli_fetch_assoc($selectResult2)) {							
				$jobHour += $row2['jobHour'];
				$totalHour += $row2['jobHour'];
			}
			echo "<tr style='vertical-align:middle;'>
					<td style='text-align:center;'>$no.</td>
					<td>$jobCurrent</td>
					<td>$descCurrent</td>
					<td style='text-align:center;'>$jobHour</td>
				</tr>";
			$no++;							
		}
	}
	
	echo "</table><br>";

	echo "<i>*Generated by Job Loading System.</i>";

?>