<?php

	header("Content-type: application/vnd.ms-excel");
	header("Content-Disposition: attachment; filename=ProjectReport$_POST[year]-$_POST[month].xls");

	echo "<b>PROJECT REPORT</b><br>";
	echo "<b>Month:</b> $_POST[month]<br>";
	echo "<b>Year:</b> $_POST[year]<br><br>";

	include "../db.php";	
	include "../function.php";

	$selectSql = "SELECT * FROM data WHERE MONTH(jobDate)=$_POST[month] 
				AND YEAR(jobDate)=$_POST[year]
				order by projectCode";

	echo "<table border=1>
			<thead><tr>
				<th>No</th>
				<th>Proj. Code</th>
				<th>Proj. Name</th>
				<th>Job Name</th>
				<th>Hours</th>
			</tr></thead>";

	$projectCurrent = '';
	$projectName = '';
	$totalHour = 0;
	$no = 1;

	$selectResult = $conn->query($selectSql);
	while($row = mysqli_fetch_assoc($selectResult)) {
		$jobHour = 0;
		$row['projectCode'] = strtoupper($row['projectCode']);
		if($row['projectCode'] != $projectCurrent){
			$projectCurrent = $row['projectCode'];

			// get proj name
			$selectSql2 = "SELECT * FROM project 
				WHERE projectCode='$projectCurrent'";

			$selectResult2 = $conn->query($selectSql2);
			if($selectResult2->num_rows > 0){
				while($row2 = mysqli_fetch_assoc($selectResult2)) {
					$projectName = $row2['projectName'];
					break;
				}
			}else{
				$projectName = 'Unknown';
			}

			$selectSql2 = "SELECT * FROM data WHERE MONTH(jobDate)=$_POST[month] 
			AND YEAR(jobDate)=$_POST[year] AND projectCode='$projectCurrent' 
			order by jobName";

			$jobCurrent = '';			

			$selectResult2 = $conn->query($selectSql2);
			while($row2 = mysqli_fetch_assoc($selectResult2)) {
				
				$jobHour = 0;
				if($jobCurrent != $row2['jobName']){
					$jobCurrent = $row2['jobName'];

					echo "<tr  style='vertical-align:middle;'>
							<td style='text-align:center;'>$no.</td>
							<td style='text-align:center;'>$projectCurrent</td>
							<td>$projectName</td>
							<td>$jobCurrent</td>";

					$selectSql3 = "SELECT * FROM data 
						WHERE MONTH(jobDate)=$_POST[month] 
						AND YEAR(jobDate)=$_POST[year]
						AND projectCode='$projectCurrent'
						AND jobName='$jobCurrent'";

					$selectResult3 = $conn->query($selectSql3);
					while($row3 = mysqli_fetch_assoc($selectResult3)) {
						$jobHour += $row3['jobHour'];
						$totalHour += $row3['jobHour'];
					}

					echo "	<td style='text-align:center;'>$jobHour</td>
						</tr>";
					$no++;
				}
			}					
		}
	}
	
	echo "</table><br>";

	echo "<i>*Generated by Job Loading System.</i>";

?>